### ISSUE TITLE
personalizer or original ?

### ISSUE THREAD

**Issue by ossplus** [leotiger/grav-plugin-shoppingcart-personalizer#1]
Hello,
Thanks for your great work.
Will you merge your shoppingcart-personalizer module and original shoppingcart into one new-shoppingcart?
Or do we need to use shoppingcart-personalizer as addon and also shoppingcart module?

**Comment by leotiger** [comment]
Right now there's a transfer request open and once approved the idea is to merge the two plugins into one. As long as this is not done you need to use both of the plugins, in fact, the personalizer will not work without Shoppingcart plugin as it is declared as a dependency.

**Comment by leotiger** [comment]
@gmplab Have you tested the plugin?

**Comment by ossplus** [comment]
Not yet.
I plan to try your personalizer this weekend.
